-- ── appril_capabilities: base de conocimiento de lo que hace Appril ──────────
-- Fuente de verdad ÚNICA de las funcionalidades del producto, editable al
-- instante (UPDATE/INSERT o vía MCP), sin redeploy. La consumen los agentes por
-- la función appril_capabilities_search (busca por dolor/tema, no vuelca todo).
-- Se aplica idéntica en los DOS proyectos Supabase (producto y CRM).

create table if not exists public.appril_capabilities (
  id          bigint generated always as identity primary key,
  orden       integer not null default 0,
  grupo       text not null,
  que_hace    text not null,
  explicacion text not null,
  publico     text not null default 'ambos' check (publico in ('paciente','profesional','ambos')),
  keywords    text not null default '',
  activa      boolean not null default true,
  updated_at  timestamptz not null default now()
);

-- Búsqueda: tsvector en español, que_hace y keywords pesan más que la explicación.
alter table public.appril_capabilities
  add column if not exists busqueda tsvector
  generated always as (
    setweight(to_tsvector('spanish', coalesce(que_hace,'')), 'A') ||
    setweight(to_tsvector('spanish', coalesce(keywords,'')), 'A') ||
    setweight(to_tsvector('spanish', coalesce(explicacion,'')), 'B')
  ) stored;
create index if not exists idx_appril_capabilities_busqueda on public.appril_capabilities using gin (busqueda);

alter table public.appril_capabilities enable row level security;
drop policy if exists appril_capabilities_read on public.appril_capabilities;
create policy appril_capabilities_read on public.appril_capabilities for select to authenticated, anon using (activa);

-- Seed (idempotente: vacía y recarga, para que re-aplicar refleje el Excel actual).
truncate public.appril_capabilities restart identity;
insert into public.appril_capabilities (orden, grupo, que_hace, explicacion, publico, keywords) values
  (0, 'Comunicación con el paciente', 'Mantiene informado al paciente', 'Appril mantiene al paciente informado antes, durante y después de su cita. Le comunica la fecha, la hora, el profesional, la sede, la modalidad de atención y cualquier instrucción relevante, para reducir confusiones y facilitar que llegue preparado.', 'paciente', 'informar paciente antes durante después instrucciones'),
  (1, 'Recordatorios y confirmación', 'Envía recordatorios automáticos de las citas', 'Appril envía recordatorios automáticos antes de cada cita sin que el profesional o su asistente tengan que escribirle manualmente a cada paciente. Los recordatorios pueden programarse según las reglas definidas por el consultorio y ayudan a reducir olvidos e inasistencias.', 'paciente', 'recordatorio automático olvido inasistencia no shows no llegan sin escribir manual perseguir'),
  (2, 'Recordatorios y confirmación', 'Solicita la confirmación de asistencia', 'Appril contacta al paciente para preguntarle si asistirá a su cita y registra automáticamente su respuesta. Así, el profesional y su equipo pueden saber quién confirmó, quién canceló y quién todavía no ha respondido, sin revisar conversaciones una por una.', 'paciente', 'confirmación asistencia quién confirmó quién no respondió inasistencia perseguir revisar chats'),
  (3, 'Recordatorios y confirmación', 'Permite que el paciente cancele con anticipación', 'Appril le ofrece al paciente una forma sencilla de cancelar su cita cuando ya no puede asistir. Al conocer la cancelación con tiempo, el espacio queda disponible para ser asignado a otro paciente y se evita descubrir una silla vacía a última hora.', 'paciente', 'cancelar anticipación silla vacía hueco recuperar espacio'),
  (4, 'Recordatorios y confirmación', 'Permite que el paciente reagende su cita', 'Appril permite que el paciente cambie su cita y seleccione otro horario disponible dentro de las reglas configuradas por el profesional. Esto reduce las conversaciones de ida y vuelta por WhatsApp y evita que el equipo tenga que buscar manualmente cada alternativa.', 'paciente', 'reagendar cambiar horario ida y vuelta whatsapp evitar buscar manual'),
  (5, 'Agenda y citas', 'Mantiene actualizada la agenda del profesional', 'Appril actualiza la agenda automáticamente cuando un paciente confirma, cancela o cambia su cita. El profesional y su equipo ven la misma información en tiempo real, lo que reduce errores, llamadas innecesarias y trabajo de actualización manual.', 'profesional', 'agenda actualizada tiempo real error llamada trabajo manual'),
  (6, 'Agenda y citas', 'Centraliza la información de cada cita', 'Appril concentra en una sola cita la información del paciente, el servicio, el profesional, la sede, la hora, el estado de confirmación, las instrucciones, los mensajes relacionados y otros datos importantes. Esto evita que la operación dependa de notas, capturas o conversaciones dispersas.', 'profesional', 'centraliza información cita notas capturas conversaciones dispersas'),
  (7, 'Agenda y citas', 'Permite crear y administrar citas', 'Appril permite registrar nuevas citas, modificar sus datos, cambiar su horario, asignarlas a un profesional, definir el tipo de servicio y registrar su estado. La agenda se convierte en el punto central de la operación diaria del consultorio.', 'profesional', 'crear administrar citas modificar asignar estado'),
  (8, 'Agenda y citas', 'Permite configurar los horarios de atención', 'Appril permite que cada profesional defina sus días y horarios de trabajo. También puede establecer jornadas diferentes por sede, servicio o día de la semana, de modo que la disponibilidad mostrada refleje la operación real del consultorio.', 'profesional', 'horarios atención días jornadas disponibilidad'),
  (9, 'Agenda y citas', 'Permite crear diferentes tipos de cita', 'Appril permite crear consultas, procedimientos, controles, valoraciones y otros tipos de servicio. Cada tipo de cita puede tener su propia duración, precio, instrucciones, modalidad, sede y reglas de disponibilidad.', 'profesional', 'tipos de cita consulta procedimiento control valoración'),
  (10, 'Agenda y citas', 'Permite definir la duración de cada servicio', 'Appril permite asignar una duración específica a cada tipo de cita. Así, una consulta inicial, un control o un procedimiento pueden ocupar tiempos diferentes sin necesidad de ajustar manualmente la agenda en cada reserva.', 'profesional', 'duración servicio tiempo por cita'),
  (11, 'Agenda y citas', 'Permite bloquear espacios no disponibles', 'Appril permite bloquear espacios por reuniones, vacaciones, almuerzos, diligencias, incapacidad, actividades personales o cualquier otra razón. Los horarios bloqueados dejan de aparecer como disponibles para evitar reservas indebidas.', 'profesional', 'bloquear espacios vacaciones almuerzo incapacidad no disponible'),
  (12, 'Multi-sede y reglas', 'Permite administrar varias sedes o consultorios', 'Appril permite registrar distintas sedes, consultorios o lugares de atención. Cada cita puede asociarse a una ubicación específica y cada sede puede tener horarios, profesionales, reglas e información propia.', 'profesional', 'varias sedes consultorios ubicación multiconsultorio'),
  (13, 'Multi-sede y reglas', 'Permite configurar reglas particulares por consultorio', 'Appril permite establecer reglas diferentes para cada consultorio o sede, como horarios, capacidad, tiempos de reserva, restricciones, tipos de servicio, mensajes e instrucciones. Esto facilita operar modelos de atención distintos dentro de una misma cuenta.', 'profesional', 'reglas por consultorio capacidad restricciones distintos'),
  (14, 'Agenda y citas', 'Permite gestionar citas presenciales y virtuales', 'Appril permite diferenciar citas presenciales, virtuales o de otra modalidad. En las citas virtuales puede incluir enlaces e instrucciones de conexión; en las presenciales puede enviar la dirección, recomendaciones de llegada y datos de la sede.', 'ambos', 'presencial virtual teleconsulta enlace conexión modalidad'),
  (15, 'Autoagendamiento y página pública', 'Permite el autoagendamiento de pacientes', 'Appril permite que los pacientes consulten los horarios disponibles y agenden una cita sin esperar a que alguien responda. El profesional conserva el control porque decide qué servicios, horarios, sedes y profesionales estarán disponibles para autoagendamiento. La funcionalidad de autoagendamiento viene deshabilitada. Si la necesita. el profesional puede habilitarla en cualquier momento', 'paciente', 'autoagendamiento paciente agenda solo sin esperar respuesta control profesional deshabilitado'),
  (16, 'Autoagendamiento y página pública', 'Permite activar o desactivar el autoagendamiento', 'Appril no obliga al profesional a permitir que los pacientes se agenden solos. Esta función puede activarse o desactivarse según la forma de trabajo del consultorio, y puede habilitarse solamente para determinados servicios o profesionales.', 'profesional', 'activar desactivar autoagendamiento por servicio profesional'),
  (17, 'Autoagendamiento y página pública', 'Permite definir con cuánta anticipación se puede agendar', 'Appril permite configurar el tiempo mínimo y máximo con el que un paciente puede reservar una cita. Esto evita reservas demasiado cercanas, protege la organización del consultorio y permite controlar cuántos días o meses hacia adelante se ofrece disponibilidad.', 'profesional', 'anticipación mínima máxima reserva días meses adelante'),
  (18, 'Autoagendamiento y página pública', 'Permite compartir un enlace de agendamiento', 'Appril genera un enlace que el profesional puede compartir por WhatsApp, redes sociales, correo electrónico, página web o cualquier otro canal. Desde ese enlace, el paciente puede consultar servicios y gestionar su cita según las opciones habilitadas.', 'ambos', 'enlace agendamiento compartir whatsapp redes correo web'),
  (19, 'Autoagendamiento y página pública', 'Ofrece una página profesional pública', 'Appril permite que cada profesional tenga una página pública con su nombre, especialidad, perfil, servicios, procedimientos, productos, sedes, horarios, información de contacto y opciones de agendamiento. Esta página funciona como una presencia profesional sencilla y como puerta de entrada a la agenda.', 'profesional', 'página pública perfil servicios presencia profesional puerta de entrada'),
  (20, 'Autoagendamiento y página pública', 'Permite mostrar servicios, productos y procedimientos', 'Appril permite publicar los servicios, productos o procedimientos que ofrece el profesional, junto con su descripción, duración, precio u otra información relevante. Esto ayuda al paciente a entender mejor la oferta antes de solicitar una cita.', 'profesional', 'mostrar servicios productos procedimientos precio descripción'),
  (21, 'Equipo y control', 'Permite crear asistentes', 'Appril permite que el profesional invite asistentes para ayudar a gestionar pacientes y citas. El profesional y sus asistentes trabajan sobre la misma agenda sincronizada, reduciendo mensajes internos, duplicidad de tareas y diferencias de información.', 'profesional', 'crear asistentes invitar equipo misma agenda sincronizada'),
  (22, 'Equipo y control', 'Permite asignar asistentes a profesionales específicos', 'Appril permite definir qué profesionales puede gestionar cada asistente. Esto facilita trabajar con equipos donde una asistente administra una sola agenda o varias, sin darle acceso innecesario a información de otros profesionales.', 'profesional', 'asignar asistentes a profesionales acceso'),
  (23, 'Equipo y control', 'Mantiene al profesional en control de la configuración', 'Appril diferencia entre las tareas operativas de la asistente y las decisiones de configuración del propietario de la agenda. El profesional mantiene el control sobre horarios, reglas, permisos, servicios y ajustes principales de su consultorio.', 'profesional', 'control configuración dueño horarios reglas permisos'),
  (24, 'Plataforma', 'Sincroniza la información entre web y aplicación móvil', 'Appril permite trabajar desde la versión web y desde la aplicación móvil. Los cambios realizados por el profesional o su asistente se reflejan en tiempo real, para que todos consulten la misma información sin importar el dispositivo utilizado.', 'profesional', 'sincroniza web aplicación móvil tiempo real dispositivo'),
  (25, 'Comunicación con el paciente', 'Permite personalizar los mensajes enviados al paciente', 'Appril permite adaptar los mensajes de confirmación, recordatorio, cancelación, reagendamiento y seguimiento al estilo del profesional. Así, la comunicación puede conservar el tono, las indicaciones y la identidad de cada consultorio.', 'profesional', 'personalizar mensajes tono identidad consultorio'),
  (26, 'Comunicación con el paciente', 'Permite enviar instrucciones específicas para una cita', 'Appril puede incluir instrucciones particulares según el servicio, como llegar en ayunas, llevar exámenes, suspender determinados productos, llegar con anticipación, preparar documentos o conectarse a un enlace. Cada paciente recibe la información necesaria para su atención.', 'paciente', 'instrucciones cita ayunas exámenes preparación documentos'),
  (27, 'Comunicación con el paciente', 'Permite adjuntar archivos y documentos a los mensajes', 'Appril permite incluir archivos, imágenes, formularios, indicaciones, mapas, consentimientos u otros documentos relacionados con la cita. Esto ayuda a preparar al paciente y reduce la necesidad de enviar información por canales separados.', 'ambos', 'adjuntar archivos imágenes formularios consentimientos mapas'),
  (28, 'Comunicación con el paciente', 'Envía comunicaciones por correo electrónico', 'Appril puede utilizar el correo electrónico para enviar confirmaciones, recordatorios, instrucciones, enlaces y otra información relacionada con la cita. El correo funciona como canal base para mantener al paciente informado de forma automática.', 'paciente', 'correo electrónico email confirmación recordatorio'),
  (29, 'Comunicación con el paciente', 'Envía comunicaciones por WhatsApp', 'Appril puede utilizar WhatsApp para enviar mensajes relacionados con la cita y permitir que el paciente responda desde un canal familiar. Este canal facilita confirmaciones, cancelaciones, reagendamientos y otras interacciones de manera más inmediata.', 'paciente', 'whatsapp canal familiar responder inmediato'),
  (30, 'Asistente IA por WhatsApp', 'Atiende solicitudes de pacientes durante todo el día', 'Appril puede funcionar como un asistente disponible las 24 horas para ayudar al paciente a consultar, confirmar, cancelar o reagendar su cita, según las funciones habilitadas. Así, el paciente no depende completamente del horario de atención del consultorio.', 'paciente', '24 horas disponible siempre fuera de horario noche consultar confirmar'),
  (31, 'Asistente IA por WhatsApp', 'Responde de forma amable y consistente', 'Appril busca que las respuestas automáticas mantengan un tono respetuoso, claro y profesional. Esto ayuda a que la experiencia del paciente sea consistente, incluso cuando realiza una solicitud fuera del horario de trabajo.', 'paciente', 'respuesta amable consistente respetuoso profesional experiencia'),
  (32, 'Asistente IA por WhatsApp', 'Permite consultar la agenda por WhatsApp', 'El profesional puede escribirle a Appril por WhatsApp para consultar información como la agenda del día, las citas de mañana, los pacientes sin confirmar o las cancelaciones de la semana. La interacción se realiza en lenguaje natural, sin depender de menús rígidos.', 'profesional', 'consultar agenda por whatsapp lenguaje natural citas de mañana sin confirmar'),
  (33, 'Asistente IA por WhatsApp', 'Envía resúmenes diarios o semanales al profesional', 'Appril puede entregar resúmenes de la agenda y de la operación, incluyendo próximas citas, confirmaciones pendientes, cancelaciones, cambios y otros datos relevantes. Estos resúmenes ayudan al profesional a mantenerse informado sin revisar toda la plataforma.', 'profesional', 'resumen diario semanal próximas citas confirmaciones pendientes sin revisar'),
  (34, 'Asistente IA por WhatsApp', 'Crea recordatorios de tareas para el profesional', 'Appril puede recordar actividades que no son citas, como pagar una factura, llamar a un paciente, enviar un documento, revisar un pendiente o completar una tarea administrativa. De esta manera, también funciona como apoyo para la organización personal del profesional.', 'profesional', 'recordatorio tarea pagar factura llamar paciente pendiente administrativo'),
  (35, 'Asistente IA por WhatsApp', 'Recuerda cobrar a un paciente antes de la cita', 'Appril puede crear recordatorios para que el profesional o su equipo soliciten un pago, anticipo o confirmación de pago antes de que el paciente llegue. Esto ayuda a ordenar el proceso de cobro y a evitar omisiones.', 'profesional', 'recordar cobrar pago anticipo antes de la cita'),
  (36, 'Pacientes e historial', 'Permite registrar y consultar información de pacientes', 'Appril permite mantener una base organizada de pacientes con sus datos de contacto, historial de citas y otra información necesaria para la operación. Esto facilita crear nuevas citas, identificar al paciente y consultar su relación con el consultorio.', 'profesional', 'registrar consultar pacientes base datos contacto historial'),
  (37, 'Pacientes e historial', 'Registra el historial de estados de una cita', 'Appril puede conservar el historial de cambios de cada cita, como creación, confirmación, cancelación, reagendamiento o finalización. Esta trazabilidad permite entender qué ocurrió y cuándo, sin depender de la memoria del equipo.', 'profesional', 'historial estados cita creación confirmación cancelación trazabilidad'),
  (38, 'Pacientes e historial', 'Permite entregar documentos verificables', 'Appril contempla la entrega de documentos como fórmulas, órdenes médicas, incapacidades, indicaciones u otros archivos relacionados con la atención. Estos documentos pueden incorporar mecanismos que permitan comprobar su autenticidad y origen.', 'ambos', 'documentos verificables fórmula orden médica incapacidad autenticidad'),
  (39, 'Reputación y satisfacción', 'Solicita valoraciones después de la atención', 'Appril puede contactar al paciente después de una cita realizada para solicitar una calificación y un comentario sobre su experiencia. Esto permite conocer la percepción del paciente mientras la atención todavía está reciente.', 'paciente', 'valoración calificación comentario después de la atención experiencia'),
  (40, 'Reputación y satisfacción', 'Recoge comentarios de los pacientes', 'Appril almacena los comentarios que los pacientes dejan después de la atención. Estos comentarios pueden revelar fortalezas, problemas recurrentes y aspectos que el profesional no siempre puede detectar durante la consulta.', 'profesional', 'comentarios pacientes fortalezas problemas detectar reputación'),
  (41, 'Reputación y satisfacción', 'Ayuda a medir la satisfacción del paciente', 'Appril permite analizar calificaciones, recomendaciones y comentarios para entender cómo están percibiendo los pacientes la atención. La satisfacción no se limita a una cifra, sino que se relaciona con temas concretos de la experiencia.', 'profesional', 'medir satisfacción calificaciones recomendaciones percepción reputación'),
  (42, 'Reputación y satisfacción', 'Convierte valoraciones positivas en piezas para compartir', 'Appril puede transformar comentarios positivos reales en textos y piezas de reputación que el profesional pueda compartir en sus redes sociales. El objetivo es reconocer su trabajo sin inventar cualidades ni utilizar afirmaciones que no estén respaldadas por los pacientes.', 'profesional', 'reseñas positivas piezas reputación redes sociales compartir sin inventar'),
  (43, 'Appril Advice (inteligencia)', 'Detecta patrones en los comentarios con inteligencia artificial', 'Appril utiliza inteligencia artificial para identificar temas que se repiten en los comentarios, incluso cuando los pacientes utilizan palabras diferentes. Puede reconocer patrones relacionados con confianza, empatía, claridad, puntualidad, espera, ambiente, seguimiento y otros aspectos de la experiencia.', 'profesional', 'inteligencia artificial patrones comentarios confianza empatía puntualidad espera'),
  (44, 'Appril Advice (inteligencia)', 'Identifica fortalezas del profesional', 'Appril puede detectar las cualidades que los pacientes mencionan de forma recurrente, como escucha, claridad, calidez, confianza, amabilidad o acompañamiento. Estas fortalezas sirven para reconocer el trabajo del profesional y reforzar aquello que genera una buena experiencia.', 'profesional', 'fortalezas escucha claridad calidez confianza amabilidad'),
  (45, 'Appril Advice (inteligencia)', 'Identifica oportunidades de mejora', 'Appril puede detectar señales repetidas de fricción o insatisfacción, como tiempos de espera, atención apresurada, falta de claridad, problemas administrativos, ausencia de seguimiento o dificultades en el proceso de agendamiento.', 'profesional', 'oportunidades mejora fricción espera atención apresurada administrativo'),
  (46, 'Appril Advice (inteligencia)', 'Ofrece recomendaciones mediante Appril Advice', 'Appril Advice interpreta los comentarios y datos de la operación para recomendar acciones concretas. No se limita a mostrar lo que dijeron los pacientes: ayuda al profesional a entender qué puede cambiar para mejorar la próxima experiencia.', 'profesional', 'Appril Advice recomienda acciones concretas mejorar experiencia'),
  (47, 'Appril Advice (inteligencia)', 'Conecta problemas detectados con playbooks expertos', 'Appril Advice puede relacionar cada patrón con un playbook de mejora. Por ejemplo, un problema de espera puede conectarse con ajustes de duración, buffers, comunicación previa o distribución de horarios, mientras que una dificultad de explicación puede generar recomendaciones diferentes.', 'profesional', 'playbook experto ajustes duración buffer comunicación'),
  (48, 'Appril Advice (inteligencia)', 'Activa acciones concretas a partir de los hallazgos', 'Appril busca que una recomendación pueda convertirse en una acción dentro del producto, como modificar una regla, crear una tarea, ajustar un mensaje, configurar un recordatorio o cambiar un proceso del consultorio. La inteligencia debe producir mejoras reales, no solamente reportes.', 'profesional', 'acción concreta modificar regla crear tarea ajustar mensaje'),
  (49, 'Appril Advice (inteligencia)', 'Mide si las mejoras producen resultados', 'Appril puede comparar la evolución de comentarios, calificaciones y patrones después de aplicar una acción. Esto permite saber si una mejora fue efectiva y construir un proceso continuo de aprendizaje sobre la experiencia del paciente.', 'profesional', 'medir resultado mejora efectiva aprendizaje continuo'),
  (50, 'Estadísticas y análisis', 'Muestra estadísticas del consultorio', 'Appril puede presentar indicadores sobre citas creadas, confirmadas, canceladas, reagendadas, realizadas o perdidas. Estas estadísticas permiten entender el desempeño de la agenda y tomar decisiones con información real.', 'profesional', 'estadísticas citas confirmadas canceladas realizadas perdidas desempeño'),
  (51, 'Estadísticas y análisis', 'Ayuda a identificar horarios con mayor demanda', 'Appril puede analizar qué días, horas, servicios, sedes o profesionales reciben más solicitudes. Esta información ayuda a organizar mejor la disponibilidad y detectar oportunidades para ampliar o redistribuir la atención.', 'profesional', 'horarios de mayor demanda días horas servicios sedes'),
  (52, 'Estadísticas y análisis', 'Ayuda a identificar espacios y capacidad desaprovechada', 'Appril puede mostrar huecos frecuentes, horas con baja ocupación, cancelaciones no recuperadas y otros espacios desaprovechados. Esto ayuda al profesional a entender dónde está perdiendo capacidad o ingresos.', 'profesional', 'capacidad desaprovechada huecos baja ocupación ingresos perdidos'),
  (53, 'Estadísticas y análisis', 'Permite analizar la operación por profesional o sede', 'Appril puede separar indicadores por profesional, sede, servicio o periodo. Esto facilita entender diferencias dentro del consultorio y tomar decisiones específicas para cada parte de la operación.', 'profesional', 'analizar por profesional sede servicio periodo'),
  (54, 'Appril Advice (inteligencia)', 'Utiliza inteligencia artificial para apoyar la atención', 'Appril utiliza inteligencia artificial para generar resúmenes, comprender solicitudes, analizar comentarios, sugerir acciones y facilitar la consulta de información. La IA debe trabajar con el contexto real del consultorio y respetar las reglas y permisos definidos.', 'profesional', 'inteligencia artificial resúmenes solicitudes sugerir contexto permisos'),
  (55, 'Asistente IA por WhatsApp', 'Ayuda a mejorar la calidad de las respuestas', 'Appril puede ayudar al profesional y a su equipo a redactar mensajes más claros, amables y útiles para los pacientes. Esto permite mantener una comunicación consistente y reducir respuestas improvisadas o confusas.', 'profesional', 'mejorar calidad respuestas mensajes claros amables'),
  (56, 'Onboarding y crecimiento', 'Acompaña al profesional durante la configuración', 'Appril guía al usuario para configurar horarios, servicios, sedes, mensajes, asistentes y recordatorios. El objetivo es que pueda llegar rápidamente a su primera cita gestionada y no abandone la plataforma por falta de orientación.', 'profesional', 'acompaña configuración horarios servicios primera cita no abandonar'),
  (57, 'Onboarding y crecimiento', 'Recomienda el siguiente paso según el uso del profesional', 'Mediante Appril Engage, la plataforma observa lo que el usuario ya configuró y lo que todavía falta. Con base en ese comportamiento, recomienda la acción de mayor impacto, como crear su primera cita, activar recordatorios, invitar a su asistente o compartir su página.', 'profesional', 'Appril Engage siguiente paso mayor impacto activar recordatorios'),
  (58, 'Onboarding y crecimiento', 'Celebra logros y muestra el valor obtenido', 'Appril puede reconocer hitos como la primera cita confirmada, el primer reagendamiento, la primera valoración positiva o una cantidad determinada de citas gestionadas. Esto ayuda al profesional a entender el valor que está recibiendo y fortalece el hábito de uso.', 'profesional', 'celebra logros primera cita confirmada hito valor hábito'),
  (59, 'Onboarding y crecimiento', 'Detecta señales de abandono y ayuda a reactivar al usuario', 'Appril puede identificar cuando un profesional dejó de configurar la cuenta, disminuyó su actividad o no utiliza una función importante. En lugar de enviar mensajes genéricos, puede ofrecer ayuda específica para superar la barrera detectada.', 'profesional', 'detecta abandono reactivar ayuda específica barrera'),
  (60, 'Equipo y control', 'Permite configurar la identidad del consultorio', 'Appril permite adaptar elementos como nombre, información profesional, mensajes, datos de contacto y otros detalles visibles para el paciente. Esto ayuda a que la comunicación se sienta propia del consultorio y no como un mensaje genérico de una plataforma.', 'profesional', 'identidad consultorio nombre información contacto propio'),
  (61, 'Equipo y control', 'Protege la operación con roles y permisos', 'Appril utiliza roles y permisos para definir qué información y acciones puede utilizar cada miembro del equipo. Esto permite que los asistentes trabajen en la agenda sin acceder a configuraciones o datos que no les corresponden.', 'profesional', 'roles permisos equipo acceso proteger operación asistente'),
  (62, 'Impacto en el consultorio', 'Reduce la dependencia de procesos manuales', 'Appril reemplaza tareas repetitivas que normalmente se realizan mediante llamadas, mensajes, notas o revisiones constantes. Al automatizar estos procesos, el consultorio puede operar con menos fricción y menor riesgo de que una tarea dependa de la memoria de alguien.', 'profesional', 'reduce procesos manuales llamadas notas memoria fricción automatizar'),
  (63, 'Impacto en el consultorio', 'Ayuda al consultorio a crecer sin aumentar proporcionalmente el trabajo', 'Appril permite gestionar más citas, pacientes, sedes o profesionales sin que el volumen de mensajes y tareas administrativas crezca en la misma proporción. La automatización ayuda a aumentar capacidad sin multiplicar el trabajo repetitivo.', 'profesional', 'crecer sin aumentar trabajo más citas pacientes sedes escalar'),
  (64, 'Impacto en el consultorio', 'Mejora la experiencia completa del paciente', 'Appril acompaña al paciente desde que busca un horario hasta después de su atención. Facilita el agendamiento, mantiene una comunicación clara, permite gestionar cambios y recoge su opinión para que la siguiente experiencia pueda ser mejor.', 'ambos', 'mejora experiencia completa paciente desde buscar horario hasta después'),
  (65, 'Comunicación con el paciente', 'Avisa al paciente cuando cambia la fecha o la hora de su cita', 'Appril notifica automáticamente al paciente cuando el profesional o su asistente modifica la fecha o la hora de una cita. El paciente recibe la información actualizada para evitar confusiones, desplazamientos innecesarios o que llegue en el horario anterior.', 'paciente', 'avisa cambio fecha hora cita modificación desplazamiento innecesario'),
  (66, 'Comunicación con el paciente', 'Avisa a los siguientes pacientes cuando hay demoras en la atención', 'El profesional puede informar una demora escribiéndole al asistente Appril por WhatsApp. Appril identifica las próximas citas y avisa a los siguientes pacientes que su atención podría comenzar más tarde, ayudándoles a ajustar su llegada y mejorando su experiencia.', 'paciente', 'avisa demora atención próximos pacientes ajustar llegada sala de espera');

-- Búsqueda por dolor/tema para los agentes. Devuelve las N más relevantes.
-- Si la query no matchea nada por full-text, cae a ILIKE sobre keywords+que_hace.
create or replace function public.appril_capabilities_search(
  p_query text, p_limit integer default 4, p_publico text default null
) returns table (grupo text, que_hace text, explicacion text, publico text)
language sql stable security definer set search_path = public as $$
  with q as (select nullif(replace(plainto_tsquery('spanish', coalesce(p_query,''))::text, '&', '|'), '')::tsquery as tsq)
  select c.grupo, c.que_hace, c.explicacion, c.publico
  from appril_capabilities c, q
  where c.activa
    and (p_publico is null or c.publico = p_publico or c.publico = 'ambos')
    and (
      (q.tsq is not null and c.busqueda @@ q.tsq)
      or c.que_hace ilike '%'||p_query||'%'
      or c.keywords ilike '%'||p_query||'%'
    )
  order by ts_rank(c.busqueda, q.tsq) desc nulls last, c.orden
  limit greatest(1, least(p_limit, 10));
$$;

-- Catálogo completo agrupado (para el espejo en appril-growth y para "qué hace Appril" completo).
create or replace function public.appril_capabilities_all()
returns table (grupo text, que_hace text, explicacion text, publico text)
language sql stable security definer set search_path = public as $$
  select grupo, que_hace, explicacion, publico
  from appril_capabilities where activa order by orden;
$$;

revoke all on function public.appril_capabilities_search(text,integer,text) from public;
revoke all on function public.appril_capabilities_all() from public;
grant execute on function public.appril_capabilities_search(text,integer,text) to anon, authenticated, service_role;
grant execute on function public.appril_capabilities_all() to anon, authenticated, service_role;
